// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../data/entities/media/file_document.dart';
import '../../data/entities/media/image_document.dart';
import '../../data/entities/media/link_document.dart';
import '../../data/entities/media/video_document.dart';
import '../../data/entities/misc/appsettings_document.dart';
import '../../data/entities/misc/profile_document.dart';
import '../../data/entities/misc/service_document.dart';
import '../../data/entities/nodes/category_node.dart';
import '../../data/entities/nodes/datapoint_node.dart';
import '../../data/entities/nodes/name_node.dart';
import '../../data/entities/timebuckets/day_bucket.dart';
import '../../data/entities/timebuckets/hour_bucket.dart';
import '../../data/entities/timebuckets/month_bucket.dart';
import '../../data/entities/timebuckets/weekday_average_bucket.dart';
import '../../data/entities/timebuckets/year_bucket.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1377075216480968336),
      name: 'AppSettingsDocument',
      lastPropertyId: const IdUid(2, 5291210423396687672),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6160881046846011768),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5291210423396687672),
            name: 'darkmode',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5450385804613899401),
      name: 'DataCategory',
      lastPropertyId: const IdUid(6, 8785319737744049413),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4040598687950197738),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3322491611382458926),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8655041659254247652),
            name: 'matchingFoldersFacebook',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1813115375191675332),
            name: 'matchingFoldersInstagram',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3042951448861428764),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 3711801644389041052),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(6, 8785319737744049413),
            name: 'dbCategory',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'dataPointNames',
            srcEntity: 'DataPointName',
            srcField: 'dataCategory')
      ]),
  ModelEntity(
      id: const IdUid(3, 810474731576423567),
      name: 'DataPoint',
      lastPropertyId: const IdUid(11, 3828976000279671914),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8907319381720147071),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2755472364575186427),
            name: 'dataPointNameId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 8560016975733672298),
            relationTarget: 'DataPointName'),
        ModelProperty(
            id: const IdUid(3, 8617124675550041635),
            name: 'stringName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2960393957204751450),
            name: 'sentimentScore',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7241701151858739311),
            name: 'sentimentText',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6753724756938344988),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 1191757302533808463),
            relationTarget: 'DataCategory'),
        ModelProperty(
            id: const IdUid(7, 5929550609605573313),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(4, 9000500768305898182),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(8, 3787504499476934020),
            name: 'searchTerms',
            type: 9,
            flags: 2048,
            indexId: const IdUid(5, 9073192400973285013)),
        ModelProperty(
            id: const IdUid(9, 8060187148752578269),
            name: 'valuesJsonBytes',
            type: 23,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 4535114532219598608),
            name: 'createdAt',
            type: 12,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 3828976000279671914),
            name: 'dbCreatedAt',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 6561882323586273587),
            name: 'images',
            targetId: const IdUid(8, 1208217324659833818)),
        ModelRelation(
            id: const IdUid(2, 3308931672337996718),
            name: 'videos',
            targetId: const IdUid(13, 7799685400187526737)),
        ModelRelation(
            id: const IdUid(3, 236315405467741367),
            name: 'files',
            targetId: const IdUid(6, 5209895180458202983)),
        ModelRelation(
            id: const IdUid(4, 2814369640294435270),
            name: 'links',
            targetId: const IdUid(9, 4741240183245989608))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 4047966780240409864),
      name: 'DataPointName',
      lastPropertyId: const IdUid(6, 3916398960063873349),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6347663086598558461),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3849952369656751079),
            name: 'count',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6102491927667189391),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6956464586775507941),
            name: 'dataCategoryId',
            type: 11,
            flags: 520,
            indexId: const IdUid(6, 3500843201815052209),
            relationTarget: 'DataCategory'),
        ModelProperty(
            id: const IdUid(5, 7284601427111756607),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(7, 8542309487057376144),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(6, 3916398960063873349),
            name: 'parentId',
            type: 11,
            flags: 520,
            indexId: const IdUid(8, 7594915326831330550),
            relationTarget: 'DataPointName')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'dataPoints',
            srcEntity: 'DataPoint',
            srcField: 'dataPointName'),
        ModelBacklink(
            name: 'children', srcEntity: 'DataPointName', srcField: 'parent')
      ]),
  ModelEntity(
      id: const IdUid(5, 802629014029983629),
      name: 'DayBucket',
      lastPropertyId: const IdUid(11, 5807312061455243648),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2194667532460034069),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6672532181584881731),
            name: 'day',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6939892276475349270),
            name: 'weekDay',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2728454278339013352),
            name: 'dateTime',
            type: 12,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5518605677399682365),
            name: 'total',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 80967307496799269),
            name: 'monthId',
            type: 11,
            flags: 520,
            indexId: const IdUid(9, 8213510188762066544),
            relationTarget: 'MonthBucket'),
        ModelProperty(
            id: const IdUid(7, 6609242394802382774),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(10, 808072812425222460),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(8, 1660896023121719795),
            name: 'dbDateTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3429185250919139752),
            name: 'dbCategorySentimentAverage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5100752458338080013),
            name: 'dbCategoryMap',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 5807312061455243648),
            name: 'dbServiceMap',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(5, 4996417359503927772),
            name: 'hours',
            targetId: const IdUid(7, 3982921471850060465)),
        ModelRelation(
            id: const IdUid(6, 8015224418681424820),
            name: 'dataPoints',
            targetId: const IdUid(3, 810474731576423567))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 5209895180458202983),
      name: 'FileDocument',
      lastPropertyId: const IdUid(7, 724495302783274270),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2961641561997842395),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 284789842009060837),
            name: 'uri',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 868467032522302829),
            name: 'data',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8971659022673789982),
            name: 'searchString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3442292194438923069),
            name: 'thumbnail',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6630183526982225183),
            name: 'relatedDatapointId',
            type: 11,
            flags: 520,
            indexId: const IdUid(11, 3807083459254511197),
            relationTarget: 'DataPoint'),
        ModelProperty(
            id: const IdUid(7, 724495302783274270),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(12, 3138110197491986694),
            relationTarget: 'ProfileDocument')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 3982921471850060465),
      name: 'HourBucket',
      lastPropertyId: const IdUid(10, 2485776444139753123),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5265987131415242021),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8100782055938366595),
            name: 'hour',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7560719981494928413),
            name: 'dateTime',
            type: 12,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8779667102088422367),
            name: 'total',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8966791347865932901),
            name: 'dayId',
            type: 11,
            flags: 520,
            indexId: const IdUid(13, 2849785314777630814),
            relationTarget: 'DayBucket'),
        ModelProperty(
            id: const IdUid(6, 5948718634853274431),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(14, 6631671213458643943),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(7, 546166391580267471),
            name: 'dbDateTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 3871612121375020322),
            name: 'dbCategorySentimentAverage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3685749717645235118),
            name: 'dbCategoryMap',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2485776444139753123),
            name: 'dbServiceMap',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(7, 3873301903812944381),
            name: 'dataPoints',
            targetId: const IdUid(3, 810474731576423567))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(8, 1208217324659833818),
      name: 'ImageDocument',
      lastPropertyId: const IdUid(8, 6908394696711887622),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7193489640505942771),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2593508083957261908),
            name: 'uri',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6118499510518594119),
            name: 'data',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7816246436098635026),
            name: 'searchString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 945256280586126769),
            name: 'mediaTags',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7295545662131456541),
            name: 'mediaTagScores',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5280239038776476817),
            name: 'relatedDatapointId',
            type: 11,
            flags: 520,
            indexId: const IdUid(15, 6953375379867857800),
            relationTarget: 'DataPoint'),
        ModelProperty(
            id: const IdUid(8, 6908394696711887622),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(16, 6200177142856269312),
            relationTarget: 'ProfileDocument')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(9, 4741240183245989608),
      name: 'LinkDocument',
      lastPropertyId: const IdUid(6, 4700305848033463251),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6038711235943271001),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5325963549188686337),
            name: 'uri',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6940499557413350918),
            name: 'data',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 190657755742471314),
            name: 'searchString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 43045556497322092),
            name: 'relatedDatapointId',
            type: 11,
            flags: 520,
            indexId: const IdUid(17, 2295686374313256983),
            relationTarget: 'DataPoint'),
        ModelProperty(
            id: const IdUid(6, 4700305848033463251),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(18, 4835952641265609796),
            relationTarget: 'ProfileDocument')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(10, 4393224676957634533),
      name: 'MonthBucket',
      lastPropertyId: const IdUid(10, 1893456898890427833),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1482376316313796076),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2810328183750539182),
            name: 'month',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3490702948197289733),
            name: 'dateTime',
            type: 12,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8276131005222926630),
            name: 'total',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5615417394741349143),
            name: 'yearId',
            type: 11,
            flags: 520,
            indexId: const IdUid(19, 4909734165872250981),
            relationTarget: 'YearBucket'),
        ModelProperty(
            id: const IdUid(6, 786622556112735356),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(20, 8671032944981888118),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(7, 3083072977889758460),
            name: 'dbDateTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6186436984894941057),
            name: 'dbCategorySentimentAverage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7248762090614003930),
            name: 'dbCategoryMap',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1893456898890427833),
            name: 'dbServiceMap',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(8, 7555696124570755653),
            name: 'days',
            targetId: const IdUid(5, 802629014029983629)),
        ModelRelation(
            id: const IdUid(9, 7080236566096402824),
            name: 'dataPoints',
            targetId: const IdUid(3, 810474731576423567))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(11, 17184818329056011),
      name: 'ProfileDocument',
      lastPropertyId: const IdUid(4, 1070298501023168923),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6152788201017857272),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5302129388619340456),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9181567039850286842),
            name: 'serviceId',
            type: 11,
            flags: 520,
            indexId: const IdUid(21, 3948544076744966769),
            relationTarget: 'ServiceDocument'),
        ModelProperty(
            id: const IdUid(4, 1070298501023168923),
            name: 'profilePictureId',
            type: 11,
            flags: 520,
            indexId: const IdUid(22, 6724438814618298608),
            relationTarget: 'ImageDocument')
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(10, 8096968180296721073),
            name: 'dataPoints',
            targetId: const IdUid(3, 810474731576423567))
      ],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'categories', srcEntity: 'DataCategory', srcField: 'profile')
      ]),
  ModelEntity(
      id: const IdUid(12, 3955481984084767355),
      name: 'ServiceDocument',
      lastPropertyId: const IdUid(5, 9064898077136200436),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4082671530694060551),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7578716425190832820),
            name: 'serviceName',
            type: 9,
            flags: 2080,
            indexId: const IdUid(23, 5925909630645139756)),
        ModelProperty(
            id: const IdUid(3, 6880810570451665316),
            name: 'companyName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 381303873300109775),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 9064898077136200436),
            name: 'totalDatapoints',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(13, 7799685400187526737),
      name: 'VideoDocument',
      lastPropertyId: const IdUid(7, 1572447599065124845),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2297445140746461505),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7427563283823559286),
            name: 'uri',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5421011629272975448),
            name: 'data',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4870498812379024194),
            name: 'searchString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2630991251360947862),
            name: 'thumbnail',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8292813956857966807),
            name: 'relatedDatapointId',
            type: 11,
            flags: 520,
            indexId: const IdUid(24, 6319446786678809665),
            relationTarget: 'DataPoint'),
        ModelProperty(
            id: const IdUid(7, 1572447599065124845),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(25, 8662547446101897287),
            relationTarget: 'ProfileDocument')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(14, 62198590062245838),
      name: 'WeekDayAverageComputed',
      lastPropertyId: const IdUid(4, 8753047251266956119),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1691712464553436419),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4406710860348910862),
            name: 'weekDay',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 887376678170403625),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(26, 5052612486917114974),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(4, 8753047251266956119),
            name: 'dbAverageCategoryMap',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(15, 5671628995633238223),
      name: 'YearBucket',
      lastPropertyId: const IdUid(9, 4274862220034290897),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3152679812767851342),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8149018912689470742),
            name: 'year',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7932807049694625991),
            name: 'dateTime',
            type: 12,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4795573860408688482),
            name: 'total',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8370880231862370147),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const IdUid(28, 3021951457458178616),
            relationTarget: 'ProfileDocument'),
        ModelProperty(
            id: const IdUid(6, 7235938527543496423),
            name: 'dbDateTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7452889912203414662),
            name: 'dbCategorySentimentAverage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 2912960482341603053),
            name: 'dbCategoryMap',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4274862220034290897),
            name: 'dbServiceMap',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(11, 1310117692775076933),
            name: 'months',
            targetId: const IdUid(10, 4393224676957634533)),
        ModelRelation(
            id: const IdUid(12, 3838390754126974260),
            name: 'dataPoints',
            targetId: const IdUid(3, 810474731576423567))
      ],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(15, 5671628995633238223),
      lastIndexId: const IdUid(28, 3021951457458178616),
      lastRelationId: const IdUid(12, 3838390754126974260),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [3293177775563472600],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    AppSettingsDocument: EntityDefinition<AppSettingsDocument>(
        model: _entities[0],
        toOneRelations: (AppSettingsDocument object) => [],
        toManyRelations: (AppSettingsDocument object) => {},
        getId: (AppSettingsDocument object) => object.id,
        setId: (AppSettingsDocument object, int id) {
          object.id = id;
        },
        objectToFB: (AppSettingsDocument object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.darkmode);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AppSettingsDocument(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false));

          return object;
        }),
    DataCategory: EntityDefinition<DataCategory>(
        model: _entities[1],
        toOneRelations: (DataCategory object) => [object.profile],
        toManyRelations: (DataCategory object) => {
              RelInfo<DataPointName>.toOneBacklink(4, object.id,
                      (DataPointName srcObject) => srcObject.dataCategory):
                  object.dataPointNames
            },
        getId: (DataCategory object) => object.id,
        setId: (DataCategory object, int id) {
          object.id = id;
        },
        objectToFB: (DataCategory object, fb.Builder fbb) {
          final matchingFoldersFacebookOffset = fbb.writeList(object
              .matchingFoldersFacebook
              .map(fbb.writeString)
              .toList(growable: false));
          final matchingFoldersInstagramOffset = fbb.writeList(object
              .matchingFoldersInstagram
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.count);
          fbb.addOffset(2, matchingFoldersFacebookOffset);
          fbb.addOffset(3, matchingFoldersInstagramOffset);
          fbb.addInt64(4, object.profile.targetId);
          fbb.addInt64(5, object.dbCategory);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DataCategory(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              count: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              matchingFoldersFacebook: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 8, []),
              matchingFoldersInstagram: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 10, []))
            ..dbCategory =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(
              object.dataPointNames,
              store,
              RelInfo<DataPointName>.toOneBacklink(4, object.id,
                  (DataPointName srcObject) => srcObject.dataCategory),
              store.box<DataCategory>());
          return object;
        }),
    DataPoint: EntityDefinition<DataPoint>(
        model: _entities[2],
        toOneRelations: (DataPoint object) =>
            [object.dataPointName, object.category, object.profile],
        toManyRelations: (DataPoint object) => {
              RelInfo<DataPoint>.toMany(1, object.id): object.images,
              RelInfo<DataPoint>.toMany(2, object.id): object.videos,
              RelInfo<DataPoint>.toMany(3, object.id): object.files,
              RelInfo<DataPoint>.toMany(4, object.id): object.links
            },
        getId: (DataPoint object) => object.id,
        setId: (DataPoint object, int id) {
          object.id = id;
        },
        objectToFB: (DataPoint object, fb.Builder fbb) {
          final stringNameOffset = fbb.writeString(object.stringName);
          final sentimentTextOffset = object.sentimentText == null
              ? null
              : fbb.writeString(object.sentimentText!);
          final searchTermsOffset = fbb.writeString(object.searchTerms);
          final valuesJsonBytesOffset =
              fbb.writeListInt8(object.valuesJsonBytes);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.dataPointName.targetId);
          fbb.addOffset(2, stringNameOffset);
          fbb.addFloat64(3, object.sentimentScore);
          fbb.addOffset(4, sentimentTextOffset);
          fbb.addInt64(5, object.category.targetId);
          fbb.addInt64(6, object.profile.targetId);
          fbb.addOffset(7, searchTermsOffset);
          fbb.addOffset(8, valuesJsonBytesOffset);
          fbb.addInt64(9, object.createdAt.microsecondsSinceEpoch * 1000);
          fbb.addInt64(10, object.dbCreatedAt);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DataPoint(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              sentimentScore: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              searchTerms: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''))
            ..stringName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..sentimentText = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..valuesJsonBytes =
                const fb.ListReader<int>(fb.Int8Reader(), lazy: false)
                    .vTableGet(buffer, rootOffset, 20, [])
            ..createdAt = DateTime.fromMicrosecondsSinceEpoch(
                (const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0) /
                        1000)
                    .round())
            ..dbCreatedAt =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.dataPointName.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.dataPointName.attach(store);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.category.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(object.images, store,
              RelInfo<DataPoint>.toMany(1, object.id), store.box<DataPoint>());
          InternalToManyAccess.setRelInfo(object.videos, store,
              RelInfo<DataPoint>.toMany(2, object.id), store.box<DataPoint>());
          InternalToManyAccess.setRelInfo(object.files, store,
              RelInfo<DataPoint>.toMany(3, object.id), store.box<DataPoint>());
          InternalToManyAccess.setRelInfo(object.links, store,
              RelInfo<DataPoint>.toMany(4, object.id), store.box<DataPoint>());
          return object;
        }),
    DataPointName: EntityDefinition<DataPointName>(
        model: _entities[3],
        toOneRelations: (DataPointName object) =>
            [object.dataCategory, object.profile, object.parent],
        toManyRelations: (DataPointName object) => {
              RelInfo<DataPoint>.toOneBacklink(2, object.id,
                      (DataPoint srcObject) => srcObject.dataPointName):
                  object.dataPoints,
              RelInfo<DataPointName>.toOneBacklink(6, object.id,
                      (DataPointName srcObject) => srcObject.parent):
                  object.children
            },
        getId: (DataPointName object) => object.id,
        setId: (DataPointName object, int id) {
          object.id = id;
        },
        objectToFB: (DataPointName object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.count);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.dataCategory.targetId);
          fbb.addInt64(4, object.profile.targetId);
          fbb.addInt64(5, object.parent.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DataPointName(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              count: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));
          object.dataCategory.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.dataCategory.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.profile.attach(store);
          object.parent.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.parent.attach(store);
          InternalToManyAccess.setRelInfo(
              object.dataPoints,
              store,
              RelInfo<DataPoint>.toOneBacklink(2, object.id,
                  (DataPoint srcObject) => srcObject.dataPointName),
              store.box<DataPointName>());
          InternalToManyAccess.setRelInfo(
              object.children,
              store,
              RelInfo<DataPointName>.toOneBacklink(
                  6, object.id, (DataPointName srcObject) => srcObject.parent),
              store.box<DataPointName>());
          return object;
        }),
    DayBucket: EntityDefinition<DayBucket>(
        model: _entities[4],
        toOneRelations: (DayBucket object) => [object.month, object.profile],
        toManyRelations: (DayBucket object) => {
              RelInfo<DayBucket>.toMany(5, object.id): object.hours,
              RelInfo<DayBucket>.toMany(6, object.id): object.dataPoints
            },
        getId: (DayBucket object) => object.id,
        setId: (DayBucket object, int id) {
          object.id = id;
        },
        objectToFB: (DayBucket object, fb.Builder fbb) {
          final dbCategorySentimentAverageOffset =
              fbb.writeString(object.dbCategorySentimentAverage);
          final dbCategoryMapOffset = fbb.writeString(object.dbCategoryMap);
          final dbServiceMapOffset = fbb.writeString(object.dbServiceMap);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.day);
          fbb.addInt64(2, object.weekDay);
          fbb.addInt64(3, object.dateTime.microsecondsSinceEpoch * 1000);
          fbb.addInt64(4, object.total);
          fbb.addInt64(5, object.month.targetId);
          fbb.addInt64(6, object.profile.targetId);
          fbb.addInt64(7, object.dbDateTime);
          fbb.addOffset(8, dbCategorySentimentAverageOffset);
          fbb.addOffset(9, dbCategoryMapOffset);
          fbb.addOffset(10, dbServiceMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DayBucket(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              total:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              day: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              weekDay:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              dateTime: DateTime.fromMicrosecondsSinceEpoch(
                  (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) /
                          1000)
                      .round()))
            ..dbDateTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..dbCategorySentimentAverage =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 20, '')
            ..dbCategoryMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '')
            ..dbServiceMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 24, '');
          object.month.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.month.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(object.hours, store,
              RelInfo<DayBucket>.toMany(5, object.id), store.box<DayBucket>());
          InternalToManyAccess.setRelInfo(object.dataPoints, store,
              RelInfo<DayBucket>.toMany(6, object.id), store.box<DayBucket>());
          return object;
        }),
    FileDocument: EntityDefinition<FileDocument>(
        model: _entities[5],
        toOneRelations: (FileDocument object) =>
            [object.relatedDatapoint, object.profile],
        toManyRelations: (FileDocument object) => {},
        getId: (FileDocument object) => object.id,
        setId: (FileDocument object, int id) {
          object.id = id;
        },
        objectToFB: (FileDocument object, fb.Builder fbb) {
          final uriOffset = fbb.writeString(object.uri);
          final dataOffset = fbb.writeString(object.data);
          final searchStringOffset = fbb.writeString(object.searchString);
          final thumbnailOffset = object.thumbnail == null
              ? null
              : fbb.writeString(object.thumbnail!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uriOffset);
          fbb.addOffset(2, dataOffset);
          fbb.addOffset(3, searchStringOffset);
          fbb.addOffset(4, thumbnailOffset);
          fbb.addInt64(5, object.relatedDatapoint.targetId);
          fbb.addInt64(6, object.profile.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FileDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              uri: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              data: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              thumbnail: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              searchString: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));
          object.relatedDatapoint.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.relatedDatapoint.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.profile.attach(store);
          return object;
        }),
    HourBucket: EntityDefinition<HourBucket>(
        model: _entities[6],
        toOneRelations: (HourBucket object) => [object.day, object.profile],
        toManyRelations: (HourBucket object) =>
            {RelInfo<HourBucket>.toMany(7, object.id): object.dataPoints},
        getId: (HourBucket object) => object.id,
        setId: (HourBucket object, int id) {
          object.id = id;
        },
        objectToFB: (HourBucket object, fb.Builder fbb) {
          final dbCategorySentimentAverageOffset =
              fbb.writeString(object.dbCategorySentimentAverage);
          final dbCategoryMapOffset = fbb.writeString(object.dbCategoryMap);
          final dbServiceMapOffset = fbb.writeString(object.dbServiceMap);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.hour);
          fbb.addInt64(2, object.dateTime.microsecondsSinceEpoch * 1000);
          fbb.addInt64(3, object.total);
          fbb.addInt64(4, object.day.targetId);
          fbb.addInt64(5, object.profile.targetId);
          fbb.addInt64(6, object.dbDateTime);
          fbb.addOffset(7, dbCategorySentimentAverageOffset);
          fbb.addOffset(8, dbCategoryMapOffset);
          fbb.addOffset(9, dbServiceMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = HourBucket(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              total:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              hour: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              dateTime: DateTime.fromMicrosecondsSinceEpoch(
                  (const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0) /
                          1000)
                      .round()))
            ..dbDateTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..dbCategorySentimentAverage =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 18, '')
            ..dbCategoryMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..dbServiceMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '');
          object.day.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.day.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(
              object.dataPoints,
              store,
              RelInfo<HourBucket>.toMany(7, object.id),
              store.box<HourBucket>());
          return object;
        }),
    ImageDocument: EntityDefinition<ImageDocument>(
        model: _entities[7],
        toOneRelations: (ImageDocument object) =>
            [object.relatedDatapoint, object.profile],
        toManyRelations: (ImageDocument object) => {},
        getId: (ImageDocument object) => object.id,
        setId: (ImageDocument object, int id) {
          object.id = id;
        },
        objectToFB: (ImageDocument object, fb.Builder fbb) {
          final uriOffset = fbb.writeString(object.uri);
          final dataOffset = fbb.writeString(object.data);
          final searchStringOffset = fbb.writeString(object.searchString);
          final mediaTagsOffset = fbb.writeString(object.mediaTags);
          final mediaTagScoresOffset = fbb.writeList(object.mediaTagScores
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uriOffset);
          fbb.addOffset(2, dataOffset);
          fbb.addOffset(3, searchStringOffset);
          fbb.addOffset(4, mediaTagsOffset);
          fbb.addOffset(5, mediaTagScoresOffset);
          fbb.addInt64(6, object.relatedDatapoint.targetId);
          fbb.addInt64(7, object.profile.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ImageDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              uri: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              data: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              searchString: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''))
            ..mediaTags = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..mediaTagScores = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 14, []);
          object.relatedDatapoint.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.relatedDatapoint.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.profile.attach(store);
          return object;
        }),
    LinkDocument: EntityDefinition<LinkDocument>(
        model: _entities[8],
        toOneRelations: (LinkDocument object) =>
            [object.relatedDatapoint, object.profile],
        toManyRelations: (LinkDocument object) => {},
        getId: (LinkDocument object) => object.id,
        setId: (LinkDocument object, int id) {
          object.id = id;
        },
        objectToFB: (LinkDocument object, fb.Builder fbb) {
          final uriOffset = fbb.writeString(object.uri);
          final dataOffset = fbb.writeString(object.data);
          final searchStringOffset = object.searchString == null
              ? null
              : fbb.writeString(object.searchString!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uriOffset);
          fbb.addOffset(2, dataOffset);
          fbb.addOffset(3, searchStringOffset);
          fbb.addInt64(4, object.relatedDatapoint.targetId);
          fbb.addInt64(5, object.profile.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = LinkDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              uri: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              data: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              searchString: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10));
          object.relatedDatapoint.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.relatedDatapoint.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.profile.attach(store);
          return object;
        }),
    MonthBucket: EntityDefinition<MonthBucket>(
        model: _entities[9],
        toOneRelations: (MonthBucket object) => [object.year, object.profile],
        toManyRelations: (MonthBucket object) => {
              RelInfo<MonthBucket>.toMany(8, object.id): object.days,
              RelInfo<MonthBucket>.toMany(9, object.id): object.dataPoints
            },
        getId: (MonthBucket object) => object.id,
        setId: (MonthBucket object, int id) {
          object.id = id;
        },
        objectToFB: (MonthBucket object, fb.Builder fbb) {
          final dbCategorySentimentAverageOffset =
              fbb.writeString(object.dbCategorySentimentAverage);
          final dbCategoryMapOffset = fbb.writeString(object.dbCategoryMap);
          final dbServiceMapOffset = fbb.writeString(object.dbServiceMap);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.month);
          fbb.addInt64(2, object.dateTime.microsecondsSinceEpoch * 1000);
          fbb.addInt64(3, object.total);
          fbb.addInt64(4, object.year.targetId);
          fbb.addInt64(5, object.profile.targetId);
          fbb.addInt64(6, object.dbDateTime);
          fbb.addOffset(7, dbCategorySentimentAverageOffset);
          fbb.addOffset(8, dbCategoryMapOffset);
          fbb.addOffset(9, dbServiceMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MonthBucket(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              total:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              month: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              dateTime: DateTime.fromMicrosecondsSinceEpoch(
                  (const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0) /
                          1000)
                      .round()))
            ..dbDateTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..dbCategorySentimentAverage =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 18, '')
            ..dbCategoryMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..dbServiceMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '');
          object.year.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.year.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(
              object.days,
              store,
              RelInfo<MonthBucket>.toMany(8, object.id),
              store.box<MonthBucket>());
          InternalToManyAccess.setRelInfo(
              object.dataPoints,
              store,
              RelInfo<MonthBucket>.toMany(9, object.id),
              store.box<MonthBucket>());
          return object;
        }),
    ProfileDocument: EntityDefinition<ProfileDocument>(
        model: _entities[10],
        toOneRelations: (ProfileDocument object) =>
            [object.service, object.profilePicture],
        toManyRelations: (ProfileDocument object) => {
              RelInfo<ProfileDocument>.toMany(10, object.id): object.dataPoints,
              RelInfo<DataCategory>.toOneBacklink(5, object.id,
                      (DataCategory srcObject) => srcObject.profile):
                  object.categories
            },
        getId: (ProfileDocument object) => object.id,
        setId: (ProfileDocument object, int id) {
          object.id = id;
        },
        objectToFB: (ProfileDocument object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.service.targetId);
          fbb.addInt64(3, object.profilePicture.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ProfileDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));
          object.service.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.service.attach(store);
          object.profilePicture.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.profilePicture.attach(store);
          InternalToManyAccess.setRelInfo(
              object.dataPoints,
              store,
              RelInfo<ProfileDocument>.toMany(10, object.id),
              store.box<ProfileDocument>());
          InternalToManyAccess.setRelInfo(
              object.categories,
              store,
              RelInfo<DataCategory>.toOneBacklink(
                  5, object.id, (DataCategory srcObject) => srcObject.profile),
              store.box<ProfileDocument>());
          return object;
        }),
    ServiceDocument: EntityDefinition<ServiceDocument>(
        model: _entities[11],
        toOneRelations: (ServiceDocument object) => [],
        toManyRelations: (ServiceDocument object) => {},
        getId: (ServiceDocument object) => object.id,
        setId: (ServiceDocument object, int id) {
          object.id = id;
        },
        objectToFB: (ServiceDocument object, fb.Builder fbb) {
          final serviceNameOffset = fbb.writeString(object.serviceName);
          final companyNameOffset = fbb.writeString(object.companyName);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, serviceNameOffset);
          fbb.addOffset(2, companyNameOffset);
          fbb.addOffset(3, imageOffset);
          fbb.addInt64(4, object.totalDatapoints);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ServiceDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              serviceName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              companyName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              totalDatapoints:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));

          return object;
        }),
    VideoDocument: EntityDefinition<VideoDocument>(
        model: _entities[12],
        toOneRelations: (VideoDocument object) =>
            [object.relatedDatapoint, object.profile],
        toManyRelations: (VideoDocument object) => {},
        getId: (VideoDocument object) => object.id,
        setId: (VideoDocument object, int id) {
          object.id = id;
        },
        objectToFB: (VideoDocument object, fb.Builder fbb) {
          final uriOffset = fbb.writeString(object.uri);
          final dataOffset = fbb.writeString(object.data);
          final searchStringOffset = fbb.writeString(object.searchString);
          final thumbnailOffset = object.thumbnail == null
              ? null
              : fbb.writeString(object.thumbnail!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uriOffset);
          fbb.addOffset(2, dataOffset);
          fbb.addOffset(3, searchStringOffset);
          fbb.addOffset(4, thumbnailOffset);
          fbb.addInt64(5, object.relatedDatapoint.targetId);
          fbb.addInt64(6, object.profile.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = VideoDocument(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              uri: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              data: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              thumbnail: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              searchString: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''));
          object.relatedDatapoint.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.relatedDatapoint.attach(store);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.profile.attach(store);
          return object;
        }),
    WeekDayAverageComputed: EntityDefinition<WeekDayAverageComputed>(
        model: _entities[13],
        toOneRelations: (WeekDayAverageComputed object) => [object.profile],
        toManyRelations: (WeekDayAverageComputed object) => {},
        getId: (WeekDayAverageComputed object) => object.id,
        setId: (WeekDayAverageComputed object, int id) {
          object.id = id;
        },
        objectToFB: (WeekDayAverageComputed object, fb.Builder fbb) {
          final dbAverageCategoryMapOffset =
              fbb.writeString(object.dbAverageCategoryMap);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.weekDay);
          fbb.addInt64(2, object.profile.targetId);
          fbb.addOffset(3, dbAverageCategoryMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = WeekDayAverageComputed(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              weekDay:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0))
            ..dbAverageCategoryMap =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 10, '');
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.profile.attach(store);
          return object;
        }),
    YearBucket: EntityDefinition<YearBucket>(
        model: _entities[14],
        toOneRelations: (YearBucket object) => [object.profile],
        toManyRelations: (YearBucket object) => {
              RelInfo<YearBucket>.toMany(11, object.id): object.months,
              RelInfo<YearBucket>.toMany(12, object.id): object.dataPoints
            },
        getId: (YearBucket object) => object.id,
        setId: (YearBucket object, int id) {
          object.id = id;
        },
        objectToFB: (YearBucket object, fb.Builder fbb) {
          final dbCategorySentimentAverageOffset =
              fbb.writeString(object.dbCategorySentimentAverage);
          final dbCategoryMapOffset = fbb.writeString(object.dbCategoryMap);
          final dbServiceMapOffset = fbb.writeString(object.dbServiceMap);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.year);
          fbb.addInt64(2, object.dateTime.microsecondsSinceEpoch * 1000);
          fbb.addInt64(3, object.total);
          fbb.addInt64(4, object.profile.targetId);
          fbb.addInt64(5, object.dbDateTime);
          fbb.addOffset(6, dbCategorySentimentAverageOffset);
          fbb.addOffset(7, dbCategoryMapOffset);
          fbb.addOffset(8, dbServiceMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = YearBucket(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              total:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              year: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              dateTime: DateTime.fromMicrosecondsSinceEpoch(
                  (const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0) /
                          1000)
                      .round()))
            ..dbDateTime =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..dbCategorySentimentAverage =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 16, '')
            ..dbCategoryMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..dbServiceMap = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '');
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.profile.attach(store);
          InternalToManyAccess.setRelInfo(
              object.months,
              store,
              RelInfo<YearBucket>.toMany(11, object.id),
              store.box<YearBucket>());
          InternalToManyAccess.setRelInfo(
              object.dataPoints,
              store,
              RelInfo<YearBucket>.toMany(12, object.id),
              store.box<YearBucket>());
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [AppSettingsDocument] entity fields to define ObjectBox queries.
class AppSettingsDocument_ {
  /// see [AppSettingsDocument.id]
  static final id =
      QueryIntegerProperty<AppSettingsDocument>(_entities[0].properties[0]);

  /// see [AppSettingsDocument.darkmode]
  static final darkmode =
      QueryBooleanProperty<AppSettingsDocument>(_entities[0].properties[1]);
}

/// [DataCategory] entity fields to define ObjectBox queries.
class DataCategory_ {
  /// see [DataCategory.id]
  static final id =
      QueryIntegerProperty<DataCategory>(_entities[1].properties[0]);

  /// see [DataCategory.count]
  static final count =
      QueryIntegerProperty<DataCategory>(_entities[1].properties[1]);

  /// see [DataCategory.matchingFoldersFacebook]
  static final matchingFoldersFacebook =
      QueryStringVectorProperty<DataCategory>(_entities[1].properties[2]);

  /// see [DataCategory.matchingFoldersInstagram]
  static final matchingFoldersInstagram =
      QueryStringVectorProperty<DataCategory>(_entities[1].properties[3]);

  /// see [DataCategory.profile]
  static final profile = QueryRelationToOne<DataCategory, ProfileDocument>(
      _entities[1].properties[4]);

  /// see [DataCategory.dbCategory]
  static final dbCategory =
      QueryIntegerProperty<DataCategory>(_entities[1].properties[5]);
}

/// [DataPoint] entity fields to define ObjectBox queries.
class DataPoint_ {
  /// see [DataPoint.id]
  static final id = QueryIntegerProperty<DataPoint>(_entities[2].properties[0]);

  /// see [DataPoint.dataPointName]
  static final dataPointName =
      QueryRelationToOne<DataPoint, DataPointName>(_entities[2].properties[1]);

  /// see [DataPoint.stringName]
  static final stringName =
      QueryStringProperty<DataPoint>(_entities[2].properties[2]);

  /// see [DataPoint.sentimentScore]
  static final sentimentScore =
      QueryDoubleProperty<DataPoint>(_entities[2].properties[3]);

  /// see [DataPoint.sentimentText]
  static final sentimentText =
      QueryStringProperty<DataPoint>(_entities[2].properties[4]);

  /// see [DataPoint.category]
  static final category =
      QueryRelationToOne<DataPoint, DataCategory>(_entities[2].properties[5]);

  /// see [DataPoint.profile]
  static final profile = QueryRelationToOne<DataPoint, ProfileDocument>(
      _entities[2].properties[6]);

  /// see [DataPoint.searchTerms]
  static final searchTerms =
      QueryStringProperty<DataPoint>(_entities[2].properties[7]);

  /// see [DataPoint.valuesJsonBytes]
  static final valuesJsonBytes =
      QueryByteVectorProperty<DataPoint>(_entities[2].properties[8]);

  /// see [DataPoint.createdAt]
  static final createdAt =
      QueryIntegerProperty<DataPoint>(_entities[2].properties[9]);

  /// see [DataPoint.dbCreatedAt]
  static final dbCreatedAt =
      QueryIntegerProperty<DataPoint>(_entities[2].properties[10]);

  /// see [DataPoint.images]
  static final images =
      QueryRelationToMany<DataPoint, ImageDocument>(_entities[2].relations[0]);

  /// see [DataPoint.videos]
  static final videos =
      QueryRelationToMany<DataPoint, VideoDocument>(_entities[2].relations[1]);

  /// see [DataPoint.files]
  static final files =
      QueryRelationToMany<DataPoint, FileDocument>(_entities[2].relations[2]);

  /// see [DataPoint.links]
  static final links =
      QueryRelationToMany<DataPoint, LinkDocument>(_entities[2].relations[3]);
}

/// [DataPointName] entity fields to define ObjectBox queries.
class DataPointName_ {
  /// see [DataPointName.id]
  static final id =
      QueryIntegerProperty<DataPointName>(_entities[3].properties[0]);

  /// see [DataPointName.count]
  static final count =
      QueryIntegerProperty<DataPointName>(_entities[3].properties[1]);

  /// see [DataPointName.name]
  static final name =
      QueryStringProperty<DataPointName>(_entities[3].properties[2]);

  /// see [DataPointName.dataCategory]
  static final dataCategory = QueryRelationToOne<DataPointName, DataCategory>(
      _entities[3].properties[3]);

  /// see [DataPointName.profile]
  static final profile = QueryRelationToOne<DataPointName, ProfileDocument>(
      _entities[3].properties[4]);

  /// see [DataPointName.parent]
  static final parent = QueryRelationToOne<DataPointName, DataPointName>(
      _entities[3].properties[5]);
}

/// [DayBucket] entity fields to define ObjectBox queries.
class DayBucket_ {
  /// see [DayBucket.id]
  static final id = QueryIntegerProperty<DayBucket>(_entities[4].properties[0]);

  /// see [DayBucket.day]
  static final day =
      QueryIntegerProperty<DayBucket>(_entities[4].properties[1]);

  /// see [DayBucket.weekDay]
  static final weekDay =
      QueryIntegerProperty<DayBucket>(_entities[4].properties[2]);

  /// see [DayBucket.dateTime]
  static final dateTime =
      QueryIntegerProperty<DayBucket>(_entities[4].properties[3]);

  /// see [DayBucket.total]
  static final total =
      QueryIntegerProperty<DayBucket>(_entities[4].properties[4]);

  /// see [DayBucket.month]
  static final month =
      QueryRelationToOne<DayBucket, MonthBucket>(_entities[4].properties[5]);

  /// see [DayBucket.profile]
  static final profile = QueryRelationToOne<DayBucket, ProfileDocument>(
      _entities[4].properties[6]);

  /// see [DayBucket.dbDateTime]
  static final dbDateTime =
      QueryIntegerProperty<DayBucket>(_entities[4].properties[7]);

  /// see [DayBucket.dbCategorySentimentAverage]
  static final dbCategorySentimentAverage =
      QueryStringProperty<DayBucket>(_entities[4].properties[8]);

  /// see [DayBucket.dbCategoryMap]
  static final dbCategoryMap =
      QueryStringProperty<DayBucket>(_entities[4].properties[9]);

  /// see [DayBucket.dbServiceMap]
  static final dbServiceMap =
      QueryStringProperty<DayBucket>(_entities[4].properties[10]);

  /// see [DayBucket.hours]
  static final hours =
      QueryRelationToMany<DayBucket, HourBucket>(_entities[4].relations[0]);

  /// see [DayBucket.dataPoints]
  static final dataPoints =
      QueryRelationToMany<DayBucket, DataPoint>(_entities[4].relations[1]);
}

/// [FileDocument] entity fields to define ObjectBox queries.
class FileDocument_ {
  /// see [FileDocument.id]
  static final id =
      QueryIntegerProperty<FileDocument>(_entities[5].properties[0]);

  /// see [FileDocument.uri]
  static final uri =
      QueryStringProperty<FileDocument>(_entities[5].properties[1]);

  /// see [FileDocument.data]
  static final data =
      QueryStringProperty<FileDocument>(_entities[5].properties[2]);

  /// see [FileDocument.searchString]
  static final searchString =
      QueryStringProperty<FileDocument>(_entities[5].properties[3]);

  /// see [FileDocument.thumbnail]
  static final thumbnail =
      QueryStringProperty<FileDocument>(_entities[5].properties[4]);

  /// see [FileDocument.relatedDatapoint]
  static final relatedDatapoint =
      QueryRelationToOne<FileDocument, DataPoint>(_entities[5].properties[5]);

  /// see [FileDocument.profile]
  static final profile = QueryRelationToOne<FileDocument, ProfileDocument>(
      _entities[5].properties[6]);
}

/// [HourBucket] entity fields to define ObjectBox queries.
class HourBucket_ {
  /// see [HourBucket.id]
  static final id =
      QueryIntegerProperty<HourBucket>(_entities[6].properties[0]);

  /// see [HourBucket.hour]
  static final hour =
      QueryIntegerProperty<HourBucket>(_entities[6].properties[1]);

  /// see [HourBucket.dateTime]
  static final dateTime =
      QueryIntegerProperty<HourBucket>(_entities[6].properties[2]);

  /// see [HourBucket.total]
  static final total =
      QueryIntegerProperty<HourBucket>(_entities[6].properties[3]);

  /// see [HourBucket.day]
  static final day =
      QueryRelationToOne<HourBucket, DayBucket>(_entities[6].properties[4]);

  /// see [HourBucket.profile]
  static final profile = QueryRelationToOne<HourBucket, ProfileDocument>(
      _entities[6].properties[5]);

  /// see [HourBucket.dbDateTime]
  static final dbDateTime =
      QueryIntegerProperty<HourBucket>(_entities[6].properties[6]);

  /// see [HourBucket.dbCategorySentimentAverage]
  static final dbCategorySentimentAverage =
      QueryStringProperty<HourBucket>(_entities[6].properties[7]);

  /// see [HourBucket.dbCategoryMap]
  static final dbCategoryMap =
      QueryStringProperty<HourBucket>(_entities[6].properties[8]);

  /// see [HourBucket.dbServiceMap]
  static final dbServiceMap =
      QueryStringProperty<HourBucket>(_entities[6].properties[9]);

  /// see [HourBucket.dataPoints]
  static final dataPoints =
      QueryRelationToMany<HourBucket, DataPoint>(_entities[6].relations[0]);
}

/// [ImageDocument] entity fields to define ObjectBox queries.
class ImageDocument_ {
  /// see [ImageDocument.id]
  static final id =
      QueryIntegerProperty<ImageDocument>(_entities[7].properties[0]);

  /// see [ImageDocument.uri]
  static final uri =
      QueryStringProperty<ImageDocument>(_entities[7].properties[1]);

  /// see [ImageDocument.data]
  static final data =
      QueryStringProperty<ImageDocument>(_entities[7].properties[2]);

  /// see [ImageDocument.searchString]
  static final searchString =
      QueryStringProperty<ImageDocument>(_entities[7].properties[3]);

  /// see [ImageDocument.mediaTags]
  static final mediaTags =
      QueryStringProperty<ImageDocument>(_entities[7].properties[4]);

  /// see [ImageDocument.mediaTagScores]
  static final mediaTagScores =
      QueryStringVectorProperty<ImageDocument>(_entities[7].properties[5]);

  /// see [ImageDocument.relatedDatapoint]
  static final relatedDatapoint =
      QueryRelationToOne<ImageDocument, DataPoint>(_entities[7].properties[6]);

  /// see [ImageDocument.profile]
  static final profile = QueryRelationToOne<ImageDocument, ProfileDocument>(
      _entities[7].properties[7]);
}

/// [LinkDocument] entity fields to define ObjectBox queries.
class LinkDocument_ {
  /// see [LinkDocument.id]
  static final id =
      QueryIntegerProperty<LinkDocument>(_entities[8].properties[0]);

  /// see [LinkDocument.uri]
  static final uri =
      QueryStringProperty<LinkDocument>(_entities[8].properties[1]);

  /// see [LinkDocument.data]
  static final data =
      QueryStringProperty<LinkDocument>(_entities[8].properties[2]);

  /// see [LinkDocument.searchString]
  static final searchString =
      QueryStringProperty<LinkDocument>(_entities[8].properties[3]);

  /// see [LinkDocument.relatedDatapoint]
  static final relatedDatapoint =
      QueryRelationToOne<LinkDocument, DataPoint>(_entities[8].properties[4]);

  /// see [LinkDocument.profile]
  static final profile = QueryRelationToOne<LinkDocument, ProfileDocument>(
      _entities[8].properties[5]);
}

/// [MonthBucket] entity fields to define ObjectBox queries.
class MonthBucket_ {
  /// see [MonthBucket.id]
  static final id =
      QueryIntegerProperty<MonthBucket>(_entities[9].properties[0]);

  /// see [MonthBucket.month]
  static final month =
      QueryIntegerProperty<MonthBucket>(_entities[9].properties[1]);

  /// see [MonthBucket.dateTime]
  static final dateTime =
      QueryIntegerProperty<MonthBucket>(_entities[9].properties[2]);

  /// see [MonthBucket.total]
  static final total =
      QueryIntegerProperty<MonthBucket>(_entities[9].properties[3]);

  /// see [MonthBucket.year]
  static final year =
      QueryRelationToOne<MonthBucket, YearBucket>(_entities[9].properties[4]);

  /// see [MonthBucket.profile]
  static final profile = QueryRelationToOne<MonthBucket, ProfileDocument>(
      _entities[9].properties[5]);

  /// see [MonthBucket.dbDateTime]
  static final dbDateTime =
      QueryIntegerProperty<MonthBucket>(_entities[9].properties[6]);

  /// see [MonthBucket.dbCategorySentimentAverage]
  static final dbCategorySentimentAverage =
      QueryStringProperty<MonthBucket>(_entities[9].properties[7]);

  /// see [MonthBucket.dbCategoryMap]
  static final dbCategoryMap =
      QueryStringProperty<MonthBucket>(_entities[9].properties[8]);

  /// see [MonthBucket.dbServiceMap]
  static final dbServiceMap =
      QueryStringProperty<MonthBucket>(_entities[9].properties[9]);

  /// see [MonthBucket.days]
  static final days =
      QueryRelationToMany<MonthBucket, DayBucket>(_entities[9].relations[0]);

  /// see [MonthBucket.dataPoints]
  static final dataPoints =
      QueryRelationToMany<MonthBucket, DataPoint>(_entities[9].relations[1]);
}

/// [ProfileDocument] entity fields to define ObjectBox queries.
class ProfileDocument_ {
  /// see [ProfileDocument.id]
  static final id =
      QueryIntegerProperty<ProfileDocument>(_entities[10].properties[0]);

  /// see [ProfileDocument.name]
  static final name =
      QueryStringProperty<ProfileDocument>(_entities[10].properties[1]);

  /// see [ProfileDocument.service]
  static final service = QueryRelationToOne<ProfileDocument, ServiceDocument>(
      _entities[10].properties[2]);

  /// see [ProfileDocument.profilePicture]
  static final profilePicture =
      QueryRelationToOne<ProfileDocument, ImageDocument>(
          _entities[10].properties[3]);

  /// see [ProfileDocument.dataPoints]
  static final dataPoints = QueryRelationToMany<ProfileDocument, DataPoint>(
      _entities[10].relations[0]);
}

/// [ServiceDocument] entity fields to define ObjectBox queries.
class ServiceDocument_ {
  /// see [ServiceDocument.id]
  static final id =
      QueryIntegerProperty<ServiceDocument>(_entities[11].properties[0]);

  /// see [ServiceDocument.serviceName]
  static final serviceName =
      QueryStringProperty<ServiceDocument>(_entities[11].properties[1]);

  /// see [ServiceDocument.companyName]
  static final companyName =
      QueryStringProperty<ServiceDocument>(_entities[11].properties[2]);

  /// see [ServiceDocument.image]
  static final image =
      QueryStringProperty<ServiceDocument>(_entities[11].properties[3]);

  /// see [ServiceDocument.totalDatapoints]
  static final totalDatapoints =
      QueryIntegerProperty<ServiceDocument>(_entities[11].properties[4]);
}

/// [VideoDocument] entity fields to define ObjectBox queries.
class VideoDocument_ {
  /// see [VideoDocument.id]
  static final id =
      QueryIntegerProperty<VideoDocument>(_entities[12].properties[0]);

  /// see [VideoDocument.uri]
  static final uri =
      QueryStringProperty<VideoDocument>(_entities[12].properties[1]);

  /// see [VideoDocument.data]
  static final data =
      QueryStringProperty<VideoDocument>(_entities[12].properties[2]);

  /// see [VideoDocument.searchString]
  static final searchString =
      QueryStringProperty<VideoDocument>(_entities[12].properties[3]);

  /// see [VideoDocument.thumbnail]
  static final thumbnail =
      QueryStringProperty<VideoDocument>(_entities[12].properties[4]);

  /// see [VideoDocument.relatedDatapoint]
  static final relatedDatapoint =
      QueryRelationToOne<VideoDocument, DataPoint>(_entities[12].properties[5]);

  /// see [VideoDocument.profile]
  static final profile = QueryRelationToOne<VideoDocument, ProfileDocument>(
      _entities[12].properties[6]);
}

/// [WeekDayAverageComputed] entity fields to define ObjectBox queries.
class WeekDayAverageComputed_ {
  /// see [WeekDayAverageComputed.id]
  static final id =
      QueryIntegerProperty<WeekDayAverageComputed>(_entities[13].properties[0]);

  /// see [WeekDayAverageComputed.weekDay]
  static final weekDay =
      QueryIntegerProperty<WeekDayAverageComputed>(_entities[13].properties[1]);

  /// see [WeekDayAverageComputed.profile]
  static final profile =
      QueryRelationToOne<WeekDayAverageComputed, ProfileDocument>(
          _entities[13].properties[2]);

  /// see [WeekDayAverageComputed.dbAverageCategoryMap]
  static final dbAverageCategoryMap =
      QueryStringProperty<WeekDayAverageComputed>(_entities[13].properties[3]);
}

/// [YearBucket] entity fields to define ObjectBox queries.
class YearBucket_ {
  /// see [YearBucket.id]
  static final id =
      QueryIntegerProperty<YearBucket>(_entities[14].properties[0]);

  /// see [YearBucket.year]
  static final year =
      QueryIntegerProperty<YearBucket>(_entities[14].properties[1]);

  /// see [YearBucket.dateTime]
  static final dateTime =
      QueryIntegerProperty<YearBucket>(_entities[14].properties[2]);

  /// see [YearBucket.total]
  static final total =
      QueryIntegerProperty<YearBucket>(_entities[14].properties[3]);

  /// see [YearBucket.profile]
  static final profile = QueryRelationToOne<YearBucket, ProfileDocument>(
      _entities[14].properties[4]);

  /// see [YearBucket.dbDateTime]
  static final dbDateTime =
      QueryIntegerProperty<YearBucket>(_entities[14].properties[5]);

  /// see [YearBucket.dbCategorySentimentAverage]
  static final dbCategorySentimentAverage =
      QueryStringProperty<YearBucket>(_entities[14].properties[6]);

  /// see [YearBucket.dbCategoryMap]
  static final dbCategoryMap =
      QueryStringProperty<YearBucket>(_entities[14].properties[7]);

  /// see [YearBucket.dbServiceMap]
  static final dbServiceMap =
      QueryStringProperty<YearBucket>(_entities[14].properties[8]);

  /// see [YearBucket.months]
  static final months =
      QueryRelationToMany<YearBucket, MonthBucket>(_entities[14].relations[0]);

  /// see [YearBucket.dataPoints]
  static final dataPoints =
      QueryRelationToMany<YearBucket, DataPoint>(_entities[14].relations[1]);
}
