name: waultar
description: Visualize Your Data

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Internationalization
    sdk: flutter         # Internationalization
  intl: ^0.17.0          # Internationalization

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6295
  fluttericon: ^2.0.0
  flutter_svg: ^0.23.0+1

  # js: any
  provider: ^6.0.1
  tuple: ^2.0.0
  file_picker: ^4.2.4
  dcdg: ^4.0.1

  font_awesome_flutter: ^9.2.0

  # for dependency injection
  get_it: ^7.2.0

  objectbox: ^1.4.1
  objectbox_flutter_libs: any

  pretty_json: ^2.0.0
  enough_convert: ^1.4.0
  deep_pick: ^0.10.0

  # to use drift query APIs with the sqlite3 lib
  # drift: ^1.0.1 

  # ships the latest sqlite3 version with the android and iOS build. Not on other platforms.
  # sqlite3_flutter_libs: ^0.5.1

  # Used to find a suitable location to store the db file. 
  path_provider: ^2.0.7
  path: ^1.8.0

  # used for zip extraction
  archive: ^3.2.1
  iconsax: ^0.0.8
  carousel_slider: ^4.0.0
  tflite: ^1.1.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  url_launcher: ^6.0.20
  easy_isolate: ^1.3.0

  # charts package
  syncfusion_flutter_charts: ^19.4.56
  syncfusion_flutter_treemap: ^19.4.56-beta
  translator: ^0.1.7
  remove_emoji: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  msix: ^2.6.3
  
  build_runner: ^2.0.0
  objectbox_generator: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/poppins/Poppins-Light.ttf
          weight: 200
        - asset: lib/assets/poppins/Poppins-Regular.ttf
          weight: 300
        - asset: lib/assets/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: lib/assets/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: lib/assets/poppins/Poppins-Bold.ttf
          weight: 700     
  
  assets:
    - lib/assets/graphics/
    - lib/assets/ai_models/
    - blobs/
    # - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Waultar
  publisher_display_name: NorseKode
  identity_name: NorseKode.Waultar.Windows
  msix_version: 0.0.1.0
  logo_path: .\lib\assets\graphics\Logo.png

objectbox: 
  output_dir: data/configs
