# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Windows msi

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test-android:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '13.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      - name: Enable Desktop
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-linux-desktop
        
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Windows Application
        run: flutter build windows
      
      - name: Build msi
        run: flutter pub run msix:create
      
       # Upload generated apk to the artifacts, is included in the github
       # action build
      - uses: actions/upload-artifact@v2
        with:
          name: Waultar.msi
          path: build/windows/runner/Release/
